image: nixos/nix

stages:
  - backend-test
  - frontend-test
  - backend-deploy
  - frontend-deploy

backend-test:
  stage: backend-test
  only:
    changes:
      - backend/**
  script:
    - nix develop
    - cd backend
    - bun install
    - bun run lint
    - bun run test

frontend-test:
  stage: frontend-test
  only:
    changes:
      - backend/views/**
      - frontend/public/**
  script:
    - nix develop
    - echo "Running frontend tests"
    - # Add your frontend test commands here

backend-deploy:
  stage: backend-deploy
  only:
    changes:
      - backend/**
  script:
    - echo "Deploy backend"

frontend-deploy:
  stage: frontend-deploy
  only:
    changes:
      - backend/views/**
      - frontend/public/**
  script:
    - echo "Deploy frontend"
