# .forgejo/workflows/ci.yml
name: CI

on:
  push:
    # branches: [ main ]
    paths: [ '**/**/package.json', 'backend/**', 'frontend/**', '.forgejo/workflows/**' ]
  pull_request:
    # branches: [ main ]
    paths: [ 'backend', 'frontend' ]

jobs:
  enforce-conventional-commit:
    runs-on: docker
    container: imbios/bun-node
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check commit msg
        run: |
          bun install
          commit_message=$(git show -s --format=%s $GITHUB_SHA)
          echo "Commit message:"
          echo "$commit_message"
          echo
          echo "$commit_message" | bunx commitlint
          
  backend-test:
    runs-on: docker
    container: imbios/bun-node
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          cd backend
          bun install

      - name: Generate static files
        run: |
          cd frontend
          bun install
          bun run build

      - name: Run backend tests
        run: |
          cd backend
          bun test

  frontend-test:
    runs-on: docker
    container: imbios/bun-node
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          cd frontend
          bun install

      - name: Run frontend tests
        run: |
          cd frontend
          bun test
