# .forgejo/workflows/ci.yml
name: CI

on:
  push:
    # branches: [ main ]
    paths:
      [
        "**/**/package.json",
        "**/**/tsconfig.json",
        "backend/**",
        "frontend/**",
        ".forgejo/workflows/**",
      ]
  pull_request:
    branches: [main]

jobs:
  enforce-conventional-commit:
    if: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'main' && github.event.pull_request.merged == true }}
    runs-on: docker
    container: imbios/bun-node
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check commit msg
        run: |
          bun install && npm rebuild
          commit_message=$(git show -s --format=%s $GITHUB_SHA)
          echo "Commit message:"
          echo "$commit_message"
          echo
          echo "$commit_message" | bunx commitlint
  test:
    runs-on: docker
    container: imbios/bun-node
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install deps
        run: bun i && npm rebuild

      - name: Run tests
        run: bun test ./test

  # backend-test:
  #   runs-on: docker
  #   container: imbios/bun-node
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Install dependencies
  #       run: |
  #         cd backend
  #         bun install

  #     - name: Generate static files
  #       run: |
  #         cd frontend
  #         bun install
  #         # cp .env.json.template .env.json
  #         bun run build:copy

  #     - name: Run backend tests
  #       run: |
  #         npm rebuild
  #         cd backend
  #         bun test ./

  # frontend-test:
  #   runs-on: docker
  #   container: imbios/bun-node
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Install dependencies & setup environment
  #       run: |
  #         cd frontend
  #         bun install
  #         # cp .env.json.template .env.json
  #         # we need to patch jsdom's xpath implementation for htmx: https://github.com/jsdom/jsdom/pull/3719
  #         cd ..
  #         git apply --directory=node_modules/jsdom jsdom-xpath-patch.diff

  #     - name: Run frontend tests
  #       run: |
  #         cd frontend
  #         bun run test
