# .forgejo/workflows/ci.yml
name: CI

on:
  push:
    branches: [ main ]
    paths: [ 'backend/**', '.forgejo/workflows/**' ]
  pull_request:
    branches: [ main ]
    paths: [ 'backend' ]

jobs:
  backend-test:
    runs-on: bun
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          cd backend
          bun install

      - name: Run backend tests
        run: |
          cd backend
          bun test

  frontend-test:
    runs-on: bun
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          cd frontend
          bun install

      - name: Run frontend tests
        run: |
          cd frontend
          bun test
